# Generated by Django 2.2.5 on 2019-09-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='field')),
                ('value', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Choices List',
                'verbose_name_plural': 'Choices List',
            },
        ),
    ]
